# Generated by Django 4.0.4 on 2022-07-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contact_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='product_type',
            field=models.CharField(choices=[('mens', 'Mens'), ('womens', 'Womens'), ('kids', 'Kids')], max_length=20),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='category_type',
            field=models.CharField(choices=[('mens', 'Mens'), ('womens', 'Womens'), ('kids', 'Kids')], max_length=20),
        ),
    ]
