# Generated by Django 4.0.4 on 2022-07-10 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_item_product_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.item'),
            preserve_default=False,
        ),
    ]
