# Generated by Django 4.0.4 on 2022-07-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_orderitem_ordered_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcategory',
            name='image',
        ),
        migrations.RemoveField(
            model_name='itemsubcategory',
            name='image',
        ),
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='payment_code',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
