# Generated by Django 4.0.4 on 2022-07-29 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_userhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userhistory',
            options={'verbose_name_plural': 'User Histories'},
        ),
    ]
